### ISSUE TITLE
My amount is not updating (wallet 1.1.5)

### ISSUE THREAD

**Issue by stramanu** [amjuarez/bytecoin#123]
I made a transaction from changelly, but the amount still be 0.00, Several weeks have passed

**Comment by dhimport** [comment]
I have the same issue and also posted some details on reddit. I've also sent an email to the email address on the website, supposedly for support, but nobody cared to answer. I sent a transaction from my wallet to another wallet 5 or more days ago, the amount was taken from my wallet, but the transaction was never received on the other wallet. I sent another transaction of 1 BCN for testing, one more time, and the same issue happened. I am using the latest version of the wallet + both wallets are 100% syncronized to the latest blocks. Any kind developer willing to help out ? Thank you!

**Comment by dakleyer** [comment]
Same issue for me. 

Is there any option outsite ofitial bytecoin wallet?

I mean, can we export private key and wallet to other platform ir order to view the transactions reflected?

**Comment by dhimport** [comment]
The issue has been fixed with wallet 1.1.7

**Comment by rasrenato** [comment]
Have to update your wallet your wallet https://bytecoin.org/static/files/BytecoinWallet-1.1.7.win64.zip

**Comment by abibell** [comment]
Have you tried moving your private keys to Bytecoin Wallet from freewallet.org? Worth trying as there seems to be issues with bcn wallet.

**Comment by arunrkaushik** [comment]
I have updated to 1.1.7 and my wallet is still 0. Could you kindly look into this.
Hash# 838718be7b2179b795edbd3e74970de8edd6f9c39b4a97e98aa959f72c5d70e6.
After the blockchain is updated, it again say update eons ago, day and 1970 time. Disconnected.
I think I am not the one who is complaining the same issue and it is for me and others to panic on this.

**Comment by dakleyer** [comment]
Thanks,

Efectively, it is fixed.
Iván Abril Palma

**Comment by jplakali** [comment]
i transferred some bytecoin from cryptonator exchange to bytecoin desktop wallet and trying to sync the wallet but its syncing at very slow speed. i changed the node to 8080 and my wallet synced in 5 minutes but my wallet balance was still 0 so i changed the node to automatic and it started syncing again from 300k blocks. is there any way to take BCN out of the wallet without syncing the wallet? i can see confirmed transaction on chainradar. please help me.

**Comment by stramanu** [comment]
Hi, for me is not fixed.. I've updated my wallet to v1.1.9.3, downloaded the last blockchain (https://blockchain.bytecoin.org/), replaced both blocks.bin and blockindexes.bin in "%APPDATA%\bytecoin " and then started the software. It has imported and syncronized succesfully all the blockchain, but my bytecoin amount still always be the same...
Please, help me....

![cattura](https://user-images.githubusercontent.com/6376061/34735719-afc137a8-f570-11e7-9a46-220647106fb2.PNG)
